# Convert one or more binary SPIR-V files into a single C++ header containing
# inline constexpr uint8_t arrays plus a name-keyed lookup table. Invoked in
# cmake script mode (-P) by PixeyShaders.cmake.

if(NOT SPV_FILES OR NOT SHADER_NAMES OR NOT HEADER_FILE)
	message(FATAL_ERROR "PixeyEmbedSpv requires SPV_FILES, SHADER_NAMES, HEADER_FILE")
endif()

list(LENGTH SPV_FILES spv_count)
list(LENGTH SHADER_NAMES name_count)
if(NOT spv_count EQUAL name_count)
	message(FATAL_ERROR "PixeyEmbedSpv: SPV_FILES and SHADER_NAMES must be the same length")
endif()

set(arrays "")
set(entries "")

math(EXPR last_index "${spv_count} - 1")
foreach(i RANGE ${last_index})
	list(GET SPV_FILES ${i} spv_file)
	list(GET SHADER_NAMES ${i} shader_name)

	string(REPLACE "." "_" symbol "${shader_name}")
	string(TOLOWER "${symbol}" symbol)
	set(symbol "${symbol}_spv")

	file(READ "${spv_file}" hex HEX)
	string(LENGTH "${hex}" hex_len)

	set(body "")
	set(byte_i 0)
	set(col 0)
	while(byte_i LESS hex_len)
		string(SUBSTRING "${hex}" ${byte_i} 2 byte)
		if(col EQUAL 0)
			string(APPEND body "\t")
		endif()
		string(APPEND body "0x${byte},")
		math(EXPR col "${col} + 1")
		if(col EQUAL 16)
			string(APPEND body "\n")
			set(col 0)
		else()
			string(APPEND body " ")
		endif()
		math(EXPR byte_i "${byte_i} + 2")
	endwhile()
	string(REGEX REPLACE "[ \n]+$" "" body "${body}")

	string(APPEND arrays "inline constexpr uint8_t ${symbol}[] =\n{\n${body}\n};\n\n")
	string(APPEND entries "\t{ \"${shader_name}\", ${symbol}, sizeof(${symbol}) },\n")
endforeach()

file(WRITE "${HEADER_FILE}"
"// Auto-generated by PixeyEmbedSpv.cmake -- do not edit.
#pragma once
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace Pixey::Shaders
{
${arrays}struct EmbeddedShader
{
	std::string_view name;
	const uint8_t* data;
	size_t size;
};

inline constexpr EmbeddedShader kEmbeddedShaders[] =
{
${entries}};

inline const EmbeddedShader* FindEmbeddedShader(std::string_view name)
{
	for (const EmbeddedShader& shader : kEmbeddedShaders)
	{
		if (shader.name == name)
		{
			return &shader;
		}
	}

	return nullptr;
}
}
")
