# Convert a binary SPIR-V file into a C++ header containing an inline
# constexpr uint8_t array. Invoked in cmake script mode (-P) by
# PixeyShaders.cmake.

if(NOT SPV_FILE OR NOT HEADER_FILE OR NOT SYMBOL)
	message(FATAL_ERROR "PixeyEmbedSpv requires SPV_FILE, HEADER_FILE, SYMBOL")
endif()

file(READ "${SPV_FILE}" hex HEX)
string(LENGTH "${hex}" hex_len)

set(body "")
set(i 0)
set(col 0)
while(i LESS hex_len)
	string(SUBSTRING "${hex}" ${i} 2 byte)
	if(col EQUAL 0)
		string(APPEND body "\t")
	endif()
	string(APPEND body "0x${byte},")
	math(EXPR col "${col} + 1")
	if(col EQUAL 16)
		string(APPEND body "\n")
		set(col 0)
	else()
		string(APPEND body " ")
	endif()
	math(EXPR i "${i} + 2")
endwhile()

string(REGEX REPLACE "[ \n]+$" "" body "${body}")

file(WRITE "${HEADER_FILE}"
"// Auto-generated by PixeyEmbedSpv.cmake -- do not edit.
#pragma once
#include <cstdint>

namespace Pixey::Shaders
{
inline constexpr uint8_t ${SYMBOL}[] =
{
${body}
};
}
")
